import { FILTERS_KEYS, FILTERS_DEFAULT_VALUES } from '@/consts/filtersConsts';

export function setFiltersByParams(searchParams) {
  return {
    [FILTERS_KEYS.SEARCH]:
      searchParams.get(FILTERS_KEYS.SEARCH) || FILTERS_DEFAULT_VALUES[FILTERS_KEYS.SEARCH],
    [FILTERS_KEYS.MIN_PRICE]:
      searchParams.get(FILTERS_KEYS.MIN_PRICE) || FILTERS_DEFAULT_VALUES[FILTERS_KEYS.MIN_PRICE],
    [FILTERS_KEYS.MAX_PRICE]:
      searchParams.get(FILTERS_KEYS.MAX_PRICE) || FILTERS_DEFAULT_VALUES[FILTERS_KEYS.MAX_PRICE],
    [FILTERS_KEYS.CATEGORY]:
      searchParams.get(FILTERS_KEYS.CATEGORY) || FILTERS_DEFAULT_VALUES[FILTERS_KEYS.CATEGORY],
  };
}
